general {
    disable_loading_bar = true
    hide_cursor = false
}

background {
    monitor = 
    path = screenshot
    blur_passes = 4
    blur_size = 7
    new_optimizations = true
    contrast = 0.8916
    brightness = 0.8172
}

input-field {
    monitor = 
    size = 300, 50
    outline_thickness = 3
    rounding = 15
    
    hide_input = false
    fade_on_empty = false
    
    inner_color = rgba(255, 255, 255, 0.1)
    outer_color = rgba(33ccffee)  # <-- ini warna border Hyprland lo bang
    font_color = rgb(255, 255, 255)
    
    placeholder_text = <i>Masukkan password...</i>
    position = 0, -20
    halign = center
    valign = center
}  
  
label {
    monitor = 
    text = $USER
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

 
